version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    environment:
      - MONGO_URI=mongodb+srv://Shiza:hello@cluster32760.ayu7hrd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster32760

    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads
    networks:
      - backend_network

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_network

volumes:
  mongo_data:

networks:
  backend_network:
